In [30]:
from tensorflow.keras.preprocessing.text import one_hot


In [31]:
sent=['the glass of milk',
           'the glass of juice',
           'the cup of tea',
           'I am a good boy',
           'I am a good developer',
           'understand the meaning of words',
           'your videos are good',]

In [ ]:
## Define the vocabulary size
voc_size=10000

In [33]:
## One hot representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[6435, 8882, 3172, 5163],
 [6435, 8882, 3172, 185],
 [6435, 5964, 3172, 8756],
 [1890, 892, 3561, 3194, 7752],
 [1890, 892, 3561, 3194, 385],
 [4796, 6435, 5947, 3172, 9325],
 [3284, 4470, 4902, 3194]]

In [34]:
## word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [35]:
import numpy as np


In [54]:
sent_len=8 # max len of sentence should be same
embeded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_len)
## pre menas putting zero at last to get 8 element uh can use pre also

In [37]:
print(embeded_docs)

[[   0    0    0    0 6435 8882 3172 5163]
 [   0    0    0    0 6435 8882 3172  185]
 [   0    0    0    0 6435 5964 3172 8756]
 [   0    0    0 1890  892 3561 3194 7752]
 [   0    0    0 1890  892 3561 3194  385]
 [   0    0    0 4796 6435 5947 3172 9325]
 [   0    0    0    0 3284 4470 4902 3194]]


In [46]:
## Feature representation
dim=10


In [56]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')
# model.build(input_shape=(None, sent_len))

c:\Users\HP\OneDrive\Desktop\Deep Learning\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


None: This is the batch size (unknown/flexible). You don’t need to specify it.

sent_len: This is the length of each input sentence, i.e., how many words/tokens are expected in each input sequence.

In [59]:
model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)         │ (8, 10)                │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [58]:
model.predict(embeded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 290ms/step


array([[ 0.01095253,  0.00864332,  0.00688281,  0.02039483,  0.00146546,
        -0.01923598, -0.0036347 ,  0.02727867, -0.04507754, -0.00650755],
       [ 0.01095253,  0.00864332,  0.00688281,  0.02039483,  0.00146546,
        -0.01923598, -0.0036347 ,  0.02727867, -0.04507754, -0.00650755],
       [ 0.01095253,  0.00864332,  0.00688281,  0.02039483,  0.00146546,
        -0.01923598, -0.0036347 ,  0.02727867, -0.04507754, -0.00650755],
       [ 0.01095253,  0.00864332,  0.00688281,  0.02039483,  0.00146546,
        -0.01923598, -0.0036347 ,  0.02727867, -0.04507754, -0.00650755],
       [-0.04794172,  0.01891622,  0.04838877, -0.04810828, -0.03699527,
         0.03726342,  0.04220842, -0.03836483,  0.01985428,  0.00308252],
       [ 0.00691832, -0.0462642 , -0.01213725,  0.04172533,  0.03984573,
         0.02000905,  0.00457   ,  0.01241229, -0.04728106, -0.000198  ],
       [-0.00826551,  0.03816673,  0.02771706,  0.01385217,  0.03859274,
         0.01790155,  0.04815904, -0.03036109

In [ ]:
embeded_docs[0]

(8,)